security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            id: App\Service\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: true
            provider: app_user_provider
            access_token:
                token_handler: App\Service\Security\AccessTokenHandler

    access_control:
        - { path: ^/api/user$, roles: [PUBLIC_ACCESS], methods: [POST] }
        - { path: ^/api/auth/token$, roles: [PUBLIC_ACCESS] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY, ROLE_USER ] }


